apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cdash-database
  name: cdash-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdash-database
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: {{ .Values.database.name }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.database.password }}
          image: postgres
          livenessProbe:
            exec:
              command:
                - pg_isready -U postgres
            failureThreshold: 120
            periodSeconds: 1
          name: cdash-postgres
          ports:
            - containerPort: {{ .Values.database.port }}
              hostPort: {{ .Values.database.port }}
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: postgresqldata
      restartPolicy: Always
      volumes:
        - name: postgresqldata
          persistentVolumeClaim:
            claimName: postgresqldata
status: {}
