apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: cdash
  name: cdash
spec:
  ingressClassName: traefik
  rules:
    - host: {{ .Values.application.host }}
      http:
        paths:
          - backend:
              service:
                name: cdash
                port:
                  number: {{ .Values.application.port }}
            path: /
            pathType: Prefix
status:
  loadBalancer: {}
