apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: cdashdata
  name: cdashdata
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Mi
status: {}
