apiVersion: v1
kind: Service
metadata:
  name: cdash
spec:
  ports:
    - name: {{ .Values.application.port | quote }}
      port: {{ .Values.application.port }}
      targetPort: {{ .Values.application.port }}
  selector:
    app: cdash
status:
  loadBalancer: {}
