apiVersion: v1
kind: Service
metadata:
  name: cdash-database
spec:
  ports:
    - name: {{ .Values.database.port | quote }}
      port: {{ .Values.database.port }}
      targetPort: {{ .Values.database.port }}
  selector:
    app: database
status:
  loadBalancer: {}
